[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [{ id = "end-of-file-fixer" }]

[[repos]]
repo = "https://github.com/scop/pre-commit-shfmt"
rev = "v3.12.0-2"
hooks = [{ id = "shfmt", files = ".*\\.sh$", args = ["-i", "2"] }]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-clang-format"
rev = "v18.1.8"
hooks = [{ id = "clang-format", files = ".*\\.(c|h)$" }]
